//! SMTP protocol client
//!
//! Handles SMTP protocol for sending email.

use crate::common::types::EmailAddress;
use crate::common::{Error, Result};
use crate::service::protocols::MailAuth;
use lettre::{
    AsyncSmtpTransport, AsyncTransport, Tokio1Executor,
    address::Envelope,
    message::{Mailbox, Message, MultiPart, SinglePart, header::ContentType},
    transport::smtp::authentication::{Credentials, Mechanism},
};

/// How an SMTP connection is protected.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum SmtpSecurity {
    /// TLS from the first byte, which is port 465.
    Tls,
    /// Plain to start with, upgraded by STARTTLS, which is port 587.
    StartTls,
    /// No encryption at all.
    Plaintext,
}

impl SmtpSecurity {
    /// Work out how to protect a connection from what the account says.
    ///
    /// The submission port, 587, is a plaintext port that upgrades. Treating it
    /// as implicit TLS makes the handshake fail against every mail provider
    /// worth naming: Gmail, Outlook and Fastmail all use 587. The failure looks
    /// like the server being unreachable, which sends somebody to check their
    /// network rather than their port.
    pub fn choose(port: u16, use_tls: bool) -> Self {
        match (use_tls, port) {
            (false, _) => SmtpSecurity::Plaintext,
            (true, 465) => SmtpSecurity::Tls,
            (true, _) => SmtpSecurity::StartTls,
        }
    }
}

/// SMTP client configuration
#[derive(Debug, Clone)]
pub struct SmtpConfig {
    pub server: String,
    pub port: u16,
    pub use_tls: bool,
    pub username: String,
}

/// Email to send
#[derive(Debug, Clone)]
pub struct Email {
    pub from: String,
    pub from_name: Option<String>,
    /// This message's own `Message-ID`, brackets and all.
    ///
    /// Required rather than optional, and never generated by the builder
    /// below. One birth site per outgoing message is what keeps the copy filed
    /// in Sent and the copy the recipient received to one identity: a builder
    /// that made its own would make a second one for the second build.
    /// [`crate::application::message_id`] owns the rule.
    pub message_id: String,
    /// Each recipient, with a name when one is known.
    ///
    /// The name is trusted by the time it reaches here: making it safe to
    /// write onto a header is [`crate::application::mail_controller::outgoing`]'s
    /// job, done once, before a message reaches this struct at all.
    pub to: Vec<EmailAddress>,
    pub cc: Vec<EmailAddress>,
    pub bcc: Vec<EmailAddress>,
    pub subject: String,
    pub body_text: String,
    pub body_html: Option<String>,
    /// The `Message-ID` of the message this answers, brackets and all.
    ///
    /// `None` for anything that is not a reply. The value is written verbatim,
    /// so whoever builds it owns the brackets:
    /// [`crate::application::threading::continuing`] does.
    pub in_reply_to: Option<String>,
    /// The whole conversation before this reply, oldest first, brackets and
    /// all, ending with the message being answered.
    ///
    /// A chain rather than one identifier. Carrying only the parent puts every
    /// reply directly under the top of the thread in the recipient's client.
    pub references: Option<String>,
    /// The files to send with it, already read.
    ///
    /// Read by [`crate::application::attaching::read_all`] rather than here, so
    /// that the part of sending which can be checked without a server stays
    /// checkable: what goes on the wire is decided by [`build_message`], which
    /// is pure.
    pub attachments: Vec<crate::application::attaching::Ready>,
}

impl Email {
    /// Create a simple email
    pub fn simple(from: String, to: String, subject: String, body: String) -> Self {
        Self {
            message_id: crate::application::message_id::fresh(&from),
            from,
            from_name: None,
            to: vec![EmailAddress::new(to, None)],
            cc: Vec::new(),
            bcc: Vec::new(),
            subject,
            body_text: body,
            body_html: None,
            in_reply_to: None,
            references: None,
            attachments: Vec::new(),
        }
    }
}

/// Turn an email into the message that goes on the wire.
///
/// Separate from sending, and pure, because this is the half that can be
/// checked without a server. Whether a file ends up on the message, and whether
/// the plain-text half survives being wrapped, are both decided here.
///
/// # The shape, and why it changes with the files
///
/// With no attachments the message is what it always was: one part for a plain
/// message, `multipart/alternative` for one with HTML. Wrapping those in
/// `multipart/mixed` anyway, to leave room for the case with files, would
/// change what every message without files looks like.
///
/// With attachments it is `multipart/mixed`: the body, whichever of those two
/// shapes it is, then one part per file. That is the nesting every mail client
/// expects. The other way round, files inside the alternative, makes them
/// alternatives to the message rather than things sent with it.
fn build_message(email: &Email) -> Result<Message> {
    let mut builder = Message::builder()
        .from(parse_mailbox(&email.from, email.from_name.as_deref())?)
        .subject(&email.subject)
        // Taken from the message rather than made here. The mail library will
        // make one if asked with nothing, and what it makes carries the name
        // of this computer, which is not something to send to a stranger.
        .message_id(Some(email.message_id.clone()));

    // What puts a reply in the conversation it answers rather than starting a
    // new one. Written verbatim by the mail library, which is why the brackets
    // are added before they get here.
    if let Some(parent) = &email.in_reply_to {
        builder = builder.in_reply_to(parent.clone());
    }
    if let Some(chain) = &email.references {
        builder = builder.references(chain.clone());
    }

    // Each recipient's name is trusted by the time it reaches here: making it
    // safe to write onto a header is mail_controller::outgoing's job, done
    // once, before a message reaches this struct at all.
    for to in &email.to {
        builder = builder.to(parse_mailbox(&to.address, to.name.as_deref())?);
    }
    for cc in &email.cc {
        builder = builder.cc(parse_mailbox(&cc.address, cc.name.as_deref())?);
    }
    // Blind means blind, and that rests on a default rather than on anything
    // written here: lettre builds the envelope from the Bcc header and then
    // removes the header, so the address reaches the server and no recipient
    // sees it. `keep_bcc()` turns that off, and must not be called. Checked
    // against lettre 0.11.22. The name is carried for type uniformity with
    // `to` and `cc`; it is functionally inert here, since the whole header
    // this name would be written on is what `keep_bcc()`'s absence removes.
    for bcc in &email.bcc {
        builder = builder.bcc(parse_mailbox(&bcc.address, bcc.name.as_deref())?);
    }

    let both_ways = |html: &str| {
        MultiPart::alternative()
            .singlepart(
                SinglePart::builder()
                    .header(ContentType::TEXT_PLAIN)
                    .body(email.body_text.clone()),
            )
            .singlepart(
                SinglePart::builder()
                    .header(ContentType::TEXT_HTML)
                    .body(html.to_string()),
            )
    };
    let plain_only = || {
        SinglePart::builder()
            .header(ContentType::TEXT_PLAIN)
            .body(email.body_text.clone())
    };

    let built = if email.attachments.is_empty() {
        match &email.body_html {
            Some(html) => builder.multipart(both_ways(html)),
            None => builder.body(email.body_text.clone()),
        }
    } else {
        let mut mixed = match &email.body_html {
            Some(html) => MultiPart::mixed().multipart(both_ways(html)),
            None => MultiPart::mixed().singlepart(plain_only()),
        };
        for file in &email.attachments {
            let kind = file.content_type.parse::<ContentType>().map_err(|e| {
                Error::Protocol(format!(
                    "{} has a content type this cannot write: {e}",
                    file.name
                ))
            })?;
            mixed = mixed.singlepart(
                lettre::message::Attachment::new(file.name.clone()).body(file.bytes.clone(), kind),
            );
        }
        builder.multipart(mixed)
    };
    built.map_err(|e| Error::Protocol(format!("Failed to build message: {}", e)))
}

/// Read one address into the form the mail library takes.
///
/// Free of `self` because [`build_message`] is, and because parsing an address
/// never depended on which server it was going to.
fn parse_mailbox(address: &str, name: Option<&str>) -> Result<Mailbox> {
    let parsed = address
        .trim()
        .parse::<lettre::Address>()
        .map_err(|e| Error::Protocol(format!("Invalid email address {}: {}", address, e)))?;
    // A name of nothing but spaces is not a name, and the mail library does not
    // treat it as one: it writes `From: "   " <ada@example.com>`, which is a
    // recipient's list showing a blank where the sender should be. Decided
    // here rather than at each caller, because every caller would have to
    // remember it and one of them would not.
    let name = name
        .map(str::trim)
        .filter(|name| !name.is_empty())
        .map(str::to_string);
    Ok(Mailbox::new(name, parsed))
}

/// SMTP client for async operations
pub struct SmtpClient {
    config: SmtpConfig,
    /// Whether this client may actually send.
    ///
    /// Sending is the one act here that cannot be taken back. A message that
    /// goes to the wrong people, or goes twice, or goes half-written, is out,
    /// and no amount of fixing the code afterwards recalls it. So a client
    /// does not send unless somebody said it may.
    may_send: bool,
}

impl SmtpClient {
    /// A client that can talk to the server and will not send.
    pub fn new(config: SmtpConfig) -> Result<Self> {
        Ok(Self {
            config,
            may_send: false,
        })
    }

    /// A client that may send.
    ///
    /// Named rather than a flag on `new`, so that every place which sends real
    /// mail is a place somebody wrote this word.
    pub fn allowed_to_send(config: SmtpConfig) -> Result<Self> {
        Ok(Self {
            config,
            may_send: true,
        })
    }

    /// Whether this client may send.
    pub const fn may_send(&self) -> bool {
        self.may_send
    }

    /// Send an email, and hand back exactly what went out.
    ///
    /// The bytes are what the Sent copy is made from. Rebuilding the message a
    /// second time to save it would be a second message: a fresh Date, a fresh
    /// Message-ID, and a Sent folder whose copy is not the mail anybody
    /// received.
    ///
    /// The Bcc header is not in them. `lettre` takes the addresses out of the
    /// header into the envelope and removes the header, which is what keeps
    /// blind copies blind, so the Sent copy records what was written and not
    /// who was blind copied. Turning that off is `keep_bcc()`, and it must not
    /// be called: it would put the addresses back on the wire for every
    /// recipient to read.
    pub async fn send_email(&self, email: Email, auth: &MailAuth) -> Result<Vec<u8>> {
        crate::service::outward::permitted(self.may_send, "send a message")?;
        tracing::info!(
            "Sending email from {} to {:?}",
            crate::common::logging::mask_email(&email.from),
            email
                .to
                .iter()
                .map(|e| crate::common::logging::mask_email(&e.address))
                .collect::<Vec<_>>()
        );

        let message = build_message(&email)?;

        let transport = self.transport(auth)?;

        // Taken before the send, because sending consumes the message.
        let sent = message.formatted();

        transport
            .send(message)
            .await
            .map_err(|e| Error::Protocol(format!("Failed to send email: {}", e)))?;

        tracing::info!("Email sent successfully");
        Ok(sent)
    }

    /// Open a transport to the account's SMTP server.
    ///
    /// A token is not a password: sent as PLAIN it is rejected, and the failure
    /// reads as a wrong password, which sends somebody off to reset one that no
    /// longer exists. So the mechanism is pinned to match the credential rather
    /// than left to negotiation.
    fn transport(&self, auth: &MailAuth) -> Result<AsyncSmtpTransport<Tokio1Executor>> {
        let (creds, mechanisms) = match auth {
            MailAuth::Password(password) => (
                Credentials::new(self.config.username.clone(), password.clone()),
                vec![Mechanism::Plain, Mechanism::Login],
            ),
            MailAuth::OAuth2(token) => (
                Credentials::new(self.config.username.clone(), token.clone()),
                vec![Mechanism::Xoauth2],
            ),
        };

        Ok(
            match SmtpSecurity::choose(self.config.port, self.config.use_tls) {
                SmtpSecurity::Tls => {
                    AsyncSmtpTransport::<Tokio1Executor>::relay(&self.config.server)
                        .map_err(|e| {
                            Error::Protocol(format!("Failed to create SMTP transport: {}", e))
                        })?
                        .port(self.config.port)
                        .credentials(creds)
                        .authentication(mechanisms)
                        .build()
                }
                SmtpSecurity::StartTls => {
                    AsyncSmtpTransport::<Tokio1Executor>::starttls_relay(&self.config.server)
                        .map_err(|e| {
                            Error::Protocol(format!("Failed to create SMTP transport: {}", e))
                        })?
                        .port(self.config.port)
                        .credentials(creds)
                        .authentication(mechanisms)
                        .build()
                }
                SmtpSecurity::Plaintext => {
                    AsyncSmtpTransport::<Tokio1Executor>::builder_dangerous(&self.config.server)
                        .port(self.config.port)
                        .credentials(creds)
                        .authentication(mechanisms)
                        .build()
                }
            },
        )
    }

    /// Send a message that is already built, as its own bytes.
    ///
    /// For a read receipt, whose shape is fixed by RFC 8098 and built in
    /// `application::receipts` where it can be read in a test. Going through
    /// the ordinary builder would mean describing a `multipart/report` to it
    /// and trusting the result, rather than sending exactly what was written.
    ///
    /// Behind the same gate as everything else that sends: a receipt is mail
    /// leaving this machine with somebody's address on it.
    pub async fn send_raw(&self, from: &str, to: &str, raw: &[u8], auth: &MailAuth) -> Result<()> {
        crate::service::outward::permitted(self.may_send, "send a read receipt")?;
        let envelope = Envelope::new(
            Some(
                from.parse()
                    .map_err(|e| Error::Protocol(format!("Invalid sender address: {e}")))?,
            ),
            vec![
                to.parse()
                    .map_err(|e| Error::Protocol(format!("Invalid recipient address: {e}")))?,
            ],
        )
        .map_err(|e| Error::Protocol(format!("Could not address the receipt: {e}")))?;

        self.transport(auth)?
            .send_raw(&envelope, raw)
            .await
            .map_err(|e| Error::Protocol(format!("Failed to send the receipt: {e}")))?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::SmtpSecurity;

    #[test]
    fn test_the_submission_port_upgrades_rather_than_starting_encrypted() {
        // 587 is the port Gmail, Outlook and Fastmail all use, and it is a
        // plaintext port that upgrades. Treating it as implicit TLS makes the
        // handshake fail in a way that reads like the server being
        // unreachable, which sends somebody to check their network.
        assert_eq!(SmtpSecurity::choose(587, true), SmtpSecurity::StartTls);
    }

    #[test]
    fn test_the_older_port_starts_encrypted() {
        assert_eq!(SmtpSecurity::choose(465, true), SmtpSecurity::Tls);
    }

    #[test]
    fn test_an_unusual_port_upgrades_rather_than_assuming() {
        // STARTTLS on a port that wants implicit TLS fails with a clear
        // protocol error. Implicit TLS on a port that wants STARTTLS hangs the
        // handshake, which is worse to diagnose.
        assert_eq!(SmtpSecurity::choose(2525, true), SmtpSecurity::StartTls);
    }

    #[test]
    fn test_encryption_turned_off_means_off() {
        assert_eq!(SmtpSecurity::choose(465, false), SmtpSecurity::Plaintext);
        assert_eq!(SmtpSecurity::choose(587, false), SmtpSecurity::Plaintext);
    }

    use super::*;

    fn plain_note() -> Email {
        Email::simple(
            "ada@example.com".to_string(),
            "sam@example.com".to_string(),
            "Tomorrow".to_string(),
            "See attached.".to_string(),
        )
    }

    fn on_the_wire(email: &Email) -> String {
        String::from_utf8_lossy(&build_message(email).expect("a message").formatted()).into_owned()
    }

    /// A message with a display name on it, and nothing else changed.
    fn note_from(name: &str) -> Email {
        Email {
            from_name: Some(name.to_string()),
            ..plain_note()
        }
    }

    #[test]
    fn test_a_sent_message_carries_an_identifier_naming_the_domain_it_is_from() {
        // Every message this program sent went out without one, so no
        // receiving client could thread it and the copy filed in Sent had an
        // empty identifier column. Exactly one is written, and its right-hand
        // side is the domain the message says it is from: the mail library's
        // own generator would put this computer's name there instead, which is
        // not something to send to a stranger.
        let sent = on_the_wire(&plain_note());

        let lines: Vec<&str> = sent
            .lines()
            .filter(|line| line.to_lowercase().starts_with("message-id:"))
            .collect();
        assert_eq!(lines.len(), 1, "{sent}");
        let value = lines[0]["Message-ID:".len()..].trim();
        assert!(value.starts_with('<') && value.ends_with('>'), "{value}");
        assert!(value.ends_with("@example.com>"), "{value}");
        assert!(!value.contains("invalid"), "{value}");
    }

    #[test]
    fn test_a_message_still_carries_a_date() {
        // The one surviving claim of the test this replaced. The mail library
        // fills a Date in when there is none, and a change to the builder that
        // lost it would leave every message undated in every list it lands in.
        assert!(on_the_wire(&plain_note()).contains("Date: "));
    }

    #[test]
    fn test_a_reply_says_which_message_it_answers() {
        // Without these two headers every reply this program sends starts a
        // new conversation in the recipient's client, which for somebody
        // working through a mailbox by ear turns one thread into a scattering
        // of unrelated messages.
        let sent = on_the_wire(&Email {
            in_reply_to: Some("<c@x>".to_string()),
            references: Some("<a@x> <c@x>".to_string()),
            ..plain_note()
        });

        assert!(sent.contains("In-Reply-To: <c@x>"), "{sent}");
        assert!(sent.contains("References: <a@x> <c@x>"), "{sent}");
    }

    #[test]
    fn test_a_message_that_is_not_a_reply_carries_neither_header() {
        // A new message with an In-Reply-To naming nothing would be a reply to
        // a message that does not exist.
        let sent = on_the_wire(&plain_note());
        assert!(!sent.contains("In-Reply-To"), "{sent}");
        assert!(!sent.contains("References:"), "{sent}");
    }

    #[test]
    fn test_a_long_chain_is_folded_rather_than_written_as_one_illegal_line() {
        // A header line over 998 characters is not a header, and a thread of
        // forty messages carries a chain that long.
        let chain: Vec<String> = (0..40).map(|n| format!("<m{n}@example.com>")).collect();
        let sent = on_the_wire(&Email {
            in_reply_to: Some("<m39@example.com>".to_string()),
            references: Some(chain.join(" ")),
            ..plain_note()
        });

        let longest = sent.lines().map(str::len).max().unwrap_or(0);
        assert!(longest <= 998, "a line of {longest} characters: {sent}");
        assert!(sent.contains("<m0@example.com>"), "{sent}");
        assert!(sent.contains("<m39@example.com>"), "{sent}");
    }

    #[test]
    fn test_a_message_goes_out_with_the_name_recipients_see() {
        // Every message went out as a bare address where every other mail
        // program sends a name. The builder could always write one; nothing
        // ever supplied it.
        let sent = on_the_wire(&note_from("Ada Lovelace"));
        assert!(
            sent.contains("From: \"Ada Lovelace\" <ada@example.com>"),
            "{sent}"
        );
    }

    #[test]
    fn test_a_message_goes_out_with_the_name_of_the_recipient_it_is_to() {
        // The mirror case: every message went out with the recipient's name
        // dropped, even when one was known, because nothing ever carried it
        // this far. `EmailAddress` already writes a name the same way for a
        // sender or a recipient, so this is the same quoting the From header
        // test above already checks, on the To header instead.
        let sent = on_the_wire(&Email {
            to: vec![EmailAddress::new(
                "charles@example.com".to_string(),
                Some("Charles Babbage".to_string()),
            )],
            ..plain_note()
        });
        assert!(
            sent.contains("To: \"Charles Babbage\" <charles@example.com>"),
            "{sent}"
        );
    }

    #[test]
    fn test_a_recipient_with_no_name_still_reaches_a_bare_address_on_the_wire() {
        // The neighbour case, and a regression guard for the refactor that
        // let a recipient carry a name at all: a recipient with none must
        // still read as a bare address, not as empty quotes in front of one.
        let sent = on_the_wire(&plain_note());
        assert!(sent.contains("To: sam@example.com"), "{sent}");
        assert!(!sent.contains("To: <"), "{sent}");
        assert!(!sent.contains("To: \"\""), "{sent}");
    }

    #[test]
    fn test_no_name_leaves_a_bare_address_rather_than_empty_brackets() {
        // What an account with nothing typed in that box sends, and what every
        // message sent before the box existed sent.
        let sent = on_the_wire(&plain_note());
        assert!(sent.contains("From: ada@example.com"), "{sent}");
        assert!(!sent.contains("From: <"), "{sent}");
        assert!(!sent.contains("From: \"\""), "{sent}");
    }

    #[test]
    fn test_a_name_that_is_only_spaces_is_no_name_at_all() {
        // The neighbour case to the one above. A name of spaces written raw
        // would be a From header starting with a quoted run of nothing.
        let sent = on_the_wire(&note_from("   "));
        assert!(sent.contains("From: ada@example.com"), "{sent}");
        assert!(!sent.contains("\" \""), "{sent}");
    }

    #[test]
    fn test_a_name_with_a_comma_stays_one_sender() {
        // Unquoted, "Smith, John <j@example.com>" is two addresses, one of
        // which does not exist. Asserted on the round trip rather than on the
        // spelling, because the mail library encodes such a name as a single
        // encoded word rather than quoting it, and both are one sender.
        let sent = on_the_wire(&note_from("Smith, John"));

        let read_back = crate::service::mime::parse(sent.as_bytes()).expect("a message to read");
        assert_eq!(
            read_back.from.len(),
            1,
            "one name became two senders: {:?}",
            read_back.from
        );
        assert_eq!(read_back.from[0].address, "ada@example.com");
        assert_eq!(read_back.from[0].name.as_deref(), Some("Smith, John"));
    }

    #[test]
    fn test_a_name_that_is_not_english_survives_the_journey() {
        // A header carries ASCII, so anything else is encoded on the way out
        // and has to come back as what was typed.
        let sent = on_the_wire(&note_from(
            "\u{418}\u{432}\u{430}\u{43d}\u{43e}\u{432} \u{418}\u{432}\u{430}\u{43d}",
        ));
        assert!(sent.contains("=?utf-8?"), "not encoded: {sent}");

        let read_back = crate::service::mime::parse(sent.as_bytes()).expect("a message to read");
        assert_eq!(
            read_back.from[0].name.as_deref(),
            Some("\u{418}\u{432}\u{430}\u{43d}\u{43e}\u{432} \u{418}\u{432}\u{430}\u{43d}"),
            "{:?}",
            read_back.from
        );
    }

    #[test]
    fn test_a_name_the_same_as_the_address_is_still_only_written_once() {
        // The neighbour case that the fixture rule exists for: two fields
        // holding one value have to stay two fields.
        let sent = on_the_wire(&note_from("ada@example.com"));
        assert_eq!(sent.matches("From:").count(), 1, "{sent}");

        let read_back = crate::service::mime::parse(sent.as_bytes()).expect("a message to read");
        assert_eq!(read_back.from.len(), 1, "{:?}", read_back.from);
        assert_eq!(read_back.from[0].address, "ada@example.com");
        assert_eq!(read_back.from[0].name.as_deref(), Some("ada@example.com"));
    }

    #[test]
    fn test_a_message_with_no_files_is_the_message_it_always_was() {
        // Wrapping every message in multipart/mixed to leave room for the case
        // with files would change what goes out for the case without them.
        let sent = on_the_wire(&plain_note());

        assert!(!sent.contains("multipart/mixed"), "{sent}");
        assert!(sent.contains("See attached."), "{sent}");
    }

    #[test]
    fn test_a_file_goes_out_with_the_message() {
        // The composer has had an Attach button since the beginning and there
        // was no part in the message for the file to become: no column in the
        // queue, no reading, and nothing here. Every other half of it worked.
        let mut email = plain_note();
        email.attachments = vec![crate::application::attaching::Ready {
            name: "report.pdf".to_string(),
            content_type: "application/pdf",
            bytes: b"%PDF-1.7 not really".to_vec(),
        }];

        let sent = on_the_wire(&email);

        assert!(sent.contains("multipart/mixed"), "{sent}");
        assert!(sent.contains("application/pdf"), "{sent}");
        assert!(sent.contains("report.pdf"), "{sent}");
        assert!(sent.contains("attachment"), "{sent}");
    }

    #[test]
    fn test_the_message_is_still_readable_both_ways_with_a_file_on_it() {
        // The alternative has to survive being wrapped. Losing the plain text
        // half leaves anybody reading without HTML looking at markup.
        let mut email = plain_note();
        email.body_html = Some("<p>See attached.</p>".to_string());
        email.attachments = vec![crate::application::attaching::Ready {
            name: "notes.txt".to_string(),
            content_type: "text/plain",
            bytes: b"hello".to_vec(),
        }];

        let sent = on_the_wire(&email);

        assert!(sent.contains("multipart/alternative"), "{sent}");
        assert!(sent.contains("multipart/mixed"), "{sent}");
        assert!(sent.contains("<p>See attached.</p>"), "{sent}");
    }

    #[test]
    fn test_smtp_client_creation() {
        let config = SmtpConfig {
            server: "smtp.example.com".to_string(),
            port: 587,
            use_tls: true,
            username: "test@example.com".to_string(),
        };
        let client = SmtpClient::new(config);
        assert!(client.is_ok());
    }

    #[test]
    fn test_email_simple() {
        let email = Email::simple(
            "sender@example.com".to_string(),
            "recipient@example.com".to_string(),
            "Test Subject".to_string(),
            "Test Body".to_string(),
        );
        assert_eq!(email.from, "sender@example.com");
        assert_eq!(
            email.to,
            vec![EmailAddress::new("recipient@example.com".to_string(), None)]
        );
        assert_eq!(email.subject, "Test Subject");
        assert_eq!(email.body_text, "Test Body");
        assert!(email.body_html.is_none());
    }

    #[test]
    fn test_email_with_html() {
        let mut email = Email::simple(
            "sender@example.com".to_string(),
            "recipient@example.com".to_string(),
            "Test".to_string(),
            "Plain text".to_string(),
        );
        email.body_html = Some("<p>HTML text</p>".to_string());
        assert!(email.body_html.is_some());
    }

    #[test]
    fn test_email_with_multiple_recipients() {
        let mut email = Email::simple(
            "sender@example.com".to_string(),
            "recipient1@example.com".to_string(),
            "Test".to_string(),
            "Body".to_string(),
        );
        email.to.push(EmailAddress::new(
            "recipient2@example.com".to_string(),
            None,
        ));
        email
            .cc
            .push(EmailAddress::new("cc@example.com".to_string(), None));
        assert_eq!(email.to.len(), 2);
        assert_eq!(email.cc.len(), 1);
    }
}

#[cfg(test)]
mod gate_tests {
    use super::*;

    fn config() -> SmtpConfig {
        SmtpConfig {
            server: "smtp.example.invalid".to_string(),
            port: 587,
            use_tls: true,
            username: "me@example.com".to_string(),
        }
    }

    #[tokio::test]
    async fn test_a_client_refuses_to_send_unless_it_was_allowed_to() {
        // Sending is the one act here that cannot be taken back, and the
        // whole path has never run for real. The refusal happens before any
        // connection is attempted, so pointing this at a real account cannot
        // put a half-written message in front of anybody.
        let client = SmtpClient::new(config()).expect("a client");
        let sent = client
            .send_email(
                Email::simple(
                    "me@example.com".to_string(),
                    "them@example.com".to_string(),
                    "Hello".to_string(),
                    "Body".to_string(),
                ),
                &MailAuth::Password("hunter2".to_string()),
            )
            .await;

        let Err(said) = sent else {
            panic!("it sent");
        };
        let said = said.to_string();
        assert!(said.contains("send a message"), "{said}");
        assert!(said.contains("Allow Changes"), "{said}");
    }

    #[tokio::test]
    async fn test_a_refused_send_says_exactly_what_every_other_refusal_says() {
        // IMAP and POP3 both ask crate::service::outward::permitted, which is
        // the one place the refusal sentence is written. SMTP used to answer
        // the same question inline instead of asking it, which is how a
        // second copy of the sentence could have drifted from the first
        // without anybody noticing. This does not go red on its own: the
        // inline copy already called the shared `refusal` function, so this
        // passes both before and after that was replaced with `permitted`.
        // It is worth keeping anyway, because it is what would catch the
        // sentence drifting apart in future.
        let client = SmtpClient::new(config()).expect("a client");
        let Err(said) = client
            .send_email(
                Email::simple(
                    "me@example.com".to_string(),
                    "them@example.com".to_string(),
                    "Hello".to_string(),
                    "Body".to_string(),
                ),
                &MailAuth::Password("hunter2".to_string()),
            )
            .await
        else {
            panic!("it sent");
        };

        assert_eq!(
            said.to_string(),
            Error::Security(crate::service::outward::refusal("send a message")).to_string()
        );
    }

    #[tokio::test]
    async fn test_a_reply_with_threading_headers_still_cannot_be_sent_with_the_gate_closed() {
        // A reply is now a different shape of message from anything that could
        // be sent before it, so it gets its own claim: nothing about carrying
        // a conversation, or a display name, moves the refusal.
        let client = SmtpClient::new(config()).expect("a client");
        let sent = client
            .send_email(
                Email {
                    from_name: Some("Ada Lovelace".to_string()),
                    in_reply_to: Some("<c@x>".to_string()),
                    references: Some("<a@x> <c@x>".to_string()),
                    ..Email::simple(
                        "me@example.com".to_string(),
                        "them@example.com".to_string(),
                        "Re: Hello".to_string(),
                        "Body".to_string(),
                    )
                },
                &MailAuth::Password("hunter2".to_string()),
            )
            .await;

        let Err(said) = sent else {
            panic!("it sent");
        };
        let said = said.to_string();
        assert!(said.contains("send a message"), "{said}");
        assert!(said.contains("Allow Changes"), "{said}");
    }

    /// A listener that says whether anything connected to it.
    ///
    /// "Nothing arrived" is only an observation if the same listener can be
    /// shown to see something arrive, which is what the second half of the test
    /// below does.
    async fn a_listener() -> (SmtpConfig, tokio::sync::mpsc::Receiver<()>) {
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
            .await
            .expect("a loopback port");
        let address = listener.local_addr().expect("the port that was taken");
        let (connected, heard) = tokio::sync::mpsc::channel(4);

        tokio::spawn(async move {
            while let Ok((stream, _)) = listener.accept().await {
                if connected.send(()).await.is_err() {
                    return;
                }
                drop(stream);
            }
        });

        (
            SmtpConfig {
                server: address.ip().to_string(),
                port: address.port(),
                // Plaintext, so the connection itself is the whole observation
                // and no handshake stands between the two halves of the test.
                use_tls: false,
                username: "me@example.com".to_string(),
            },
            heard,
        )
    }

    #[tokio::test]
    async fn test_nothing_reaches_a_server_with_the_gate_closed_and_something_does_when_it_is_open()
    {
        let (config, mut heard) = a_listener().await;
        let a_message = || Email {
            from_name: Some("Ada Lovelace".to_string()),
            in_reply_to: Some("<c@x>".to_string()),
            references: Some("<a@x> <c@x>".to_string()),
            ..Email::simple(
                "me@example.com".to_string(),
                "them@example.com".to_string(),
                "Re: Hello".to_string(),
                "Body".to_string(),
            )
        };

        // Closed. Built the way production builds it when the account is not
        // allowed to send.
        let refused = SmtpClient::new(config.clone())
            .expect("a client")
            .send_email(a_message(), &MailAuth::Password("hunter2".to_string()))
            .await;
        assert!(refused.is_err(), "it sent");
        assert!(
            heard.try_recv().is_err(),
            "something connected to the server with the gate closed"
        );

        // Open. The send still fails, because nothing on the other end speaks
        // SMTP, but the connection is made, which is what proves the listener
        // above can see a connection at all.
        let _ = SmtpClient::allowed_to_send(config)
            .expect("a client")
            .send_email(a_message(), &MailAuth::Password("hunter2".to_string()))
            .await;
        let saw_something = tokio::time::timeout(std::time::Duration::from_secs(5), heard.recv())
            .await
            .expect("the listener to be reached within five seconds");
        assert!(
            saw_something.is_some(),
            "the listener never saw a connection, so it could never have seen one"
        );
    }

    #[test]
    fn test_a_client_that_was_allowed_says_so() {
        assert!(!SmtpClient::new(config()).expect("a client").may_send());
        assert!(
            SmtpClient::allowed_to_send(config())
                .expect("a client")
                .may_send()
        );
    }
}

/// Sending, past the gate, against a server that answers.
///
/// The gate's refusing half was measured long before this; its permitting half
/// never was, anywhere. Nothing here proves Gmail or Fastmail accept what goes
/// out. It proves what goes out: the envelope, the headers, and the bytes that
/// become the copy filed in Sent.
///
/// Every message is ASCII on purpose. The script advertises 8BITMIME, so a
/// non-ASCII body would pass today, and a later change to the script would
/// quietly change what is being tested.
#[cfg(test)]
pub(crate) mod against_a_server_that_answers {
    use super::*;
    use crate::common::answering::{Conversation, LONG_ENOUGH, Turn, conversing};

    /// A sending server that answers the whole exchange.
    ///
    /// The advertised AUTH line is not decoration. [`SmtpClient::transport`]
    /// always sets credentials, and the mail library refuses to open a session
    /// at all, before a single byte of the message, when the greeting offers no
    /// mechanism it knows.
    ///
    /// Anything unscripted is refused rather than ignored, so a script that has
    /// fallen behind the client fails the test in the moment instead of leaving
    /// it to wait out a timeout, which reads as a slow machine.
    pub(crate) async fn an_smtp_server() -> Conversation {
        conversing("220 loopback ready\r\n", |line| {
            let said = line.to_uppercase();
            let verb = said.split_whitespace().next().unwrap_or_default();
            match verb {
                "EHLO" | "HELO" => Turn::Say(
                    "250-loopback\r\n250-AUTH PLAIN LOGIN\r\n250-8BITMIME\r\n250 SMTPUTF8\r\n"
                        .to_string(),
                ),
                "AUTH" => Turn::Say("235 authenticated\r\n".to_string()),
                "MAIL" => Turn::Say("250 sender ok\r\n".to_string()),
                "RCPT" => Turn::Say("250 recipient ok\r\n".to_string()),
                "DATA" => Turn::TakingAMessage {
                    done: "250 queued as 1\r\n".to_string(),
                },
                "QUIT" => Turn::Say("221 bye\r\n".to_string()),
                "RSET" | "NOOP" => Turn::Say("250 ok\r\n".to_string()),
                _ => Turn::Say("500 unscripted\r\n".to_string()),
            }
        })
        .await
    }

    /// An account pointed at that server, unencrypted.
    ///
    /// Plaintext, so the conversation itself is the whole observation and no
    /// handshake stands between the test and what was said.
    pub(crate) fn pointed_at(server: &Conversation) -> SmtpConfig {
        SmtpConfig {
            server: server.server(),
            port: server.port(),
            use_tls: false,
            username: "me@example.com".to_string(),
        }
    }

    fn a_message() -> Email {
        Email {
            from_name: Some("Ada Lovelace".to_string()),
            in_reply_to: Some("<c@x>".to_string()),
            references: Some("<a@x> <c@x>".to_string()),
            ..Email::simple(
                "me@example.com".to_string(),
                "them@example.com".to_string(),
                "Re: Hello".to_string(),
                "Body".to_string(),
            )
        }
    }

    /// The message body the server was given, as one block.
    ///
    /// The transcript holds it as an entry of its own, which is the only entry
    /// that is not a command line.
    async fn the_body(server: &Conversation) -> String {
        server
            .transcript()
            .await
            .into_iter()
            .find(|entry| entry.contains("Subject:"))
            .unwrap_or_default()
    }

    /// Send, and fail with a sentence rather than waiting out a timeout.
    async fn sending(client: &SmtpClient, email: Email) -> Result<Vec<u8>> {
        tokio::time::timeout(
            LONG_ENOUGH,
            client.send_email(email, &MailAuth::Password("hunter2".to_string())),
        )
        .await
        .expect("the server never finished the exchange")
    }

    #[tokio::test]
    async fn test_a_message_sent_past_an_open_gate_reaches_the_server_envelope_and_all() {
        // The whole path, for the first time. Everything before this stopped
        // at the refusal or at the connection, so the envelope, the threading
        // headers and the sender's name had never been seen by anything.
        let server = an_smtp_server().await;
        let client = SmtpClient::allowed_to_send(pointed_at(&server)).expect("a client");

        let sent = sending(&client, a_message()).await.expect("it to send");

        let transcript = server.transcript().await;
        let from = server
            .when_told("MAIL FROM:<me@example.com>")
            .await
            .unwrap_or_else(|| panic!("the sender never reached the server: {transcript:?}"));
        let to = server
            .when_told("RCPT TO:<them@example.com>")
            .await
            .unwrap_or_else(|| panic!("the recipient never reached the server: {transcript:?}"));
        let data = server
            .when_told("DATA")
            .await
            .unwrap_or_else(|| panic!("the message was never offered: {transcript:?}"));
        assert!(
            from < to && to < data,
            "the envelope was not built before the message: {transcript:?}"
        );

        let body = the_body(&server).await;
        assert!(body.contains("Subject: Re: Hello"), "{body}");
        assert!(
            body.contains("From: \"Ada Lovelace\" <me@example.com>"),
            "{body}"
        );
        assert!(body.contains("In-Reply-To: <c@x>"), "{body}");
        assert!(body.contains("References: <a@x> <c@x>"), "{body}");

        // The bytes handed back are what the copy filed in Sent is made from,
        // and they are the same bytes the server was given rather than a
        // second build of the same message.
        let sent = String::from_utf8_lossy(&sent).into_owned();
        assert_eq!(
            sent.trim_end_matches(['\r', '\n']),
            body.trim_end_matches(['\r', '\n']),
            "the copy filed in Sent is not the message that went out"
        );
    }

    #[tokio::test]
    async fn test_the_identifier_on_the_wire_is_the_one_filed_in_sent() {
        // One message, one identity. The bytes handed back are what the copy
        // in Sent is made from, so if a later change ever rebuilds the message
        // to file it, or generates an identifier inside the builder instead of
        // taking the one the message carries, the two copies stop being the
        // same message and neither of them says so.
        let server = an_smtp_server().await;
        let client = SmtpClient::allowed_to_send(pointed_at(&server)).expect("a client");

        let sent = sending(&client, a_message()).await.expect("it to send");

        let body = the_body(&server).await;
        let on_the_wire = identifier_in(&body);
        assert!(on_the_wire.ends_with("@example.com>"), "{body}");
        assert_eq!(
            on_the_wire,
            identifier_in(&String::from_utf8_lossy(&sent)),
            "the copy filed in Sent carries a different identifier from the              message the server was given"
        );
    }

    /// The one `Message-ID` a message carries, and a failure if there are two.
    fn identifier_in(message: &str) -> String {
        let found: Vec<&str> = message
            .lines()
            .filter(|line| line.to_lowercase().starts_with("message-id:"))
            .collect();
        assert_eq!(found.len(), 1, "{message}");
        found[0]["Message-ID:".len()..].trim().to_string()
    }

    #[tokio::test]
    async fn test_a_blind_copy_reaches_the_server_and_never_the_message() {
        // Blind means blind, and it rests on a default in the mail library
        // rather than on anything written here: the address is taken out of
        // the header into the envelope and the header removed. Until now that
        // was held together by a comment. If it ever stops being true, every
        // blind address goes into the Sent copy and into every recipient's
        // headers, and nothing says so.
        let server = an_smtp_server().await;
        let client = SmtpClient::allowed_to_send(pointed_at(&server)).expect("a client");

        let sent = sending(
            &client,
            Email {
                bcc: vec![EmailAddress::new("quiet@example.com".to_string(), None)],
                ..a_message()
            },
        )
        .await
        .expect("it to send");

        assert!(
            server.was_told("RCPT TO:<quiet@example.com>").await,
            "the blind copy never reached the server: {:?}",
            server.transcript().await
        );
        let body = the_body(&server).await;
        assert!(
            !body.contains("quiet@example.com"),
            "the blind address is in the message every recipient reads: {body}"
        );
        assert!(
            !String::from_utf8_lossy(&sent).contains("quiet@example.com"),
            "the blind address is in the copy filed in Sent"
        );
    }

    #[tokio::test]
    async fn test_every_recipient_gets_an_envelope_line_of_their_own() {
        // A recipient missing from the envelope is a recipient who never
        // receives the message, whatever the headers say.
        let server = an_smtp_server().await;
        let client = SmtpClient::allowed_to_send(pointed_at(&server)).expect("a client");

        sending(
            &client,
            Email {
                cc: vec![EmailAddress::new("copied@example.com".to_string(), None)],
                bcc: vec![EmailAddress::new("quiet@example.com".to_string(), None)],
                ..a_message()
            },
        )
        .await
        .expect("it to send");

        let addressed: Vec<String> = server
            .transcript()
            .await
            .into_iter()
            .filter(|line| line.to_uppercase().starts_with("RCPT TO:"))
            .collect();
        assert_eq!(addressed.len(), 3, "{addressed:?}");
        for who in [
            "them@example.com",
            "copied@example.com",
            "quiet@example.com",
        ] {
            assert!(
                addressed.iter().any(|line| line.contains(who)),
                "{who} was left out: {addressed:?}"
            );
        }
    }

    #[tokio::test]
    async fn test_a_read_receipt_goes_out_as_it_was_written() {
        // A receipt's shape is fixed by RFC 8098 and built where it can be
        // read in a test. The whole reason this path exists is that the
        // builder must not touch it, and nothing had ever checked that the
        // bytes handed in are the bytes that leave.
        let server = an_smtp_server().await;
        let client = SmtpClient::allowed_to_send(pointed_at(&server)).expect("a client");
        let raw = "From: me@example.com\r\nTo: them@example.com\r\n\
             Subject: Read receipt\r\nContent-Type: multipart/report\r\n\r\n\
             The message was displayed.\r\n";

        tokio::time::timeout(
            LONG_ENOUGH,
            client.send_raw(
                "me@example.com",
                "them@example.com",
                raw.as_bytes(),
                &MailAuth::Password("hunter2".to_string()),
            ),
        )
        .await
        .expect("the server never finished the exchange")
        .expect("the receipt to send");

        assert!(server.was_told("MAIL FROM:<me@example.com>").await);
        assert!(server.was_told("RCPT TO:<them@example.com>").await);
        let body = the_body(&server).await;
        // The sending library ends a body with a line of its own, so what the
        // server holds is the receipt followed by a blank line.
        assert_eq!(
            body.trim_end_matches(['\r', '\n']),
            raw.trim_end_matches(['\r', '\n'])
        );
    }

    #[tokio::test]
    async fn test_nothing_is_said_to_the_server_with_the_gate_closed() {
        // Stronger than "nothing connected", which is what the older check
        // measured, and it only means anything because the tests above show
        // this same server records everything it hears.
        let server = an_smtp_server().await;
        let client = SmtpClient::new(pointed_at(&server)).expect("a client");

        let refused = sending(&client, a_message()).await;

        let Err(said) = refused else {
            panic!("it sent");
        };
        let said = said.to_string();
        assert!(said.contains("send a message"), "{said}");
        assert!(said.contains("Allow Changes"), "{said}");
        assert!(
            server.transcript().await.is_empty(),
            "something was said to the server with the gate closed: {:?}",
            server.transcript().await
        );
    }

    #[tokio::test]
    async fn test_nothing_is_said_to_the_server_when_a_receipt_is_refused() {
        // A receipt is mail leaving this machine with somebody's address on
        // it, so it is behind the same gate and gets the same claim.
        let server = an_smtp_server().await;
        let client = SmtpClient::new(pointed_at(&server)).expect("a client");

        let refused = tokio::time::timeout(
            LONG_ENOUGH,
            client.send_raw(
                "me@example.com",
                "them@example.com",
                b"From: me@example.com\r\n\r\nread\r\n",
                &MailAuth::Password("hunter2".to_string()),
            ),
        )
        .await
        .expect("the refusal to be immediate");

        let Err(said) = refused else {
            panic!("it sent");
        };
        let said = said.to_string();
        assert!(said.contains("send a read receipt"), "{said}");
        assert!(said.contains("Allow Changes"), "{said}");
        assert!(
            server.transcript().await.is_empty(),
            "something was said to the server with the gate closed: {:?}",
            server.transcript().await
        );
    }
}
