//! Application layer - Business logic and managers
//!
//! This layer contains the core business logic and management components.

pub mod accounts;
pub mod allowed;
pub mod attaching;
pub mod autosave;
pub mod body_safety;
pub mod caldav_sync;
pub mod calendar;
pub mod calendar_source;
pub mod categories;
pub mod closing;
pub mod collection_sync;
pub mod contact_groups;
pub mod contacts_sync;
pub mod context_menu;
pub mod deleting_at_the_server;
pub mod deletions;
pub mod destinations;
pub mod draft_copy;
pub mod draft_message;
pub mod due;
pub mod filters;
pub mod forget;
pub mod from_message;
pub mod help;
pub mod importing_contacts;
pub mod item_fields;
pub mod local_delete;
pub mod local_folders;
pub mod long_text;
pub mod mail_auth;
pub mod mail_controller;
pub mod mail_session;
pub mod mail_sync;
pub mod message_id;
pub mod messages;
pub mod new_item;
pub mod occurrences;
pub mod pim_command;
pub mod pop_sync;
pub mod reading_habits;
pub mod reading_style;
pub mod receipts;
pub mod repeating;
pub mod reply;
pub mod running;
pub mod scrolling;
pub mod search;
pub mod sent_copy;
pub mod server_delete;
pub mod sign_off;
pub mod spell_session;
pub mod summing_up;
pub mod sync_marker;
pub mod tagging;
pub mod tasks_sync;
pub mod threading;
pub mod words;

pub use accounts::AccountManager;
pub use caldav_sync::{refresh_subscription, sync_caldav_calendar};
pub use filters::FilterEngine;
pub use mail_controller::{MailController, SendEmailRequest};
pub use search::SearchEngine;
